import turtle

"""
Библиотека turtle - позволяет создавать оконные приложение с графикой
"""
turtle.bgcolor("#3e3d9c") #задний фон
turtle.color("#000000") #цвет заливки
for i in range(4):
    turtle.forward(100)
    turtle.right(90)
turtle.begin_fill()
turtle.color("#500465")
turtle.left(45)
turtle.forward(70)
turtle.right(90)
turtle.forward(70)
turtle.end_fill()
turtle.color("#345663")
turtle.begin_fill()
turtle.right(45)
for i in range(4):
    turtle.forward(100)
    turtle.right(90)
turtle.end_fill()
turtle.color("#000000")
for i in range(4):
    turtle.forward(100)
    turtle.right(90)
turtle.pu()
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(25)
turtle.pd()
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(25)
turtle.end_fill()
turtle.pu()
turtle.color("#b4befa")
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(10)
turtle.pd()
turtle.begin_fill()
turtle.circle(3)
turtle.end_fill()
turtle.pu()
turtle.goto(0,0)
turtle.left(90)
turtle.forward(50)
turtle.right(270)
turtle.forward(10)
turtle.pd()
for f in range(2):
    for i in range(4):
        turtle.forward(20)
        turtle.left(90)
    turtle.forward(20)
turtle.right(90)
turtle.forward(20)
for i in range(2):
    for j in range(4):
        turtle.right(90)
        turtle.forward(20)
    turtle.right(90)
    turtle.forward(40)
turtle.pu()
turtle.goto(0,0)
turtle.forward(100)
turtle.color("#f7d219")
turtle.pd()
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()
turtle.pensize(5)
turtle.left(90)
turtle.forward(25)
turtle.end_fill()
for i in range(10):
    turtle.forward(35)
    turtle.backward(35)
    turtle.right(36)
turtle.color("#2adb41")
turtle.pu()
turtle.goto(0,0)
turtle.forward(30)
turtle.pd()
turtle.begin_fill()
for i in range(9):
    turtle.circle(8)
    turtle.forward(10)
    turtle.right(45)
turtle.end_fill()
turtle.pu()
turtle.right(225)
turtle.forward(10)
turtle.pd()
turtle.begin_fill()
turtle.color("#4a351a")
turtle.forward(40)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(10)
turtle.end_fill()
turtle.mainloop()
